# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 4d6455a1a92784e7502214fa9a4fb935b1de3cec

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/5/
Content-Type: application/json
Authorization: Token 4d6455a1a92784e7502214fa9a4fb935b1de3cec

{
  "status": "OPEN"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=1
Content-Type: application/json

###

# фильтрация по статусу
GET {{baseUrl}}/advertisements/?status=OPEN
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_after=2023-05-27
Content-Type: application/json

###

# создание черновика
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 4d6455a1a92784e7502214fa9a4fb935b1de3cec

{
  "title": "Шкаф IKEA",
  "description": "Срочно",
  "status": "DRAFT"
}

###


# получение объявлений с токеном
GET {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 4d6455a1a92784e7502214fa9a4fb935b1de3cec

