# Generated by Django 4.2 on 2023-05-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("measurement", "0005_measurement_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="measurement",
            name="image",
        ),
        migrations.AddField(
            model_name="measurement",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
