# Generated by Django 4.2 on 2023-04-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_alter_book_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.CharField(max_length=64, verbose_name="Author"),
        ),
        migrations.AlterField(
            model_name="book",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="name",
            field=models.CharField(max_length=64, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="book",
            name="pub_date",
            field=models.DateField(verbose_name="pub_date"),
        ),
    ]
